# -*- coding: utf-8 -*-
"""Sale_Dt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeYNeNMefUJy2cgT5W-kymFHUeRWw7Lv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("sale_data.csv")

df.head()

df.drop("Unnamed: 0", axis= 1, inplace = True)

df["Total"]= df["Quantity"] * df["Price"]

male_sales = df.loc[df['Gender'] == "Male"]
female_sales = df.loc[df['Gender'] == "Female"]

male_sales["Total"].sum()

female_sales["Total"].sum()

human_gender = ["male", "female"]

plt.bar(human_gender,[male_sales["Total"].sum(), female_sales["Total"].sum()], color = ["orange", "black"])
plt.title("Total Sales by Gender")
plt.xlabel("Gender")
plt.ylabel("Total Sales")
plt.show()

male_total= male_sales["Total"].sum()
male_total

female_total = female_sales["Total"].sum()
female_total

plt.plot([12,13,11,14], "r--o")
plt.plot([13,10,13,15], "g--o")
plt.show()

df.head()

df_male = male_sales.groupby(["Gender", "Product"])["Total"].sum().reset_index()
df_male

df

df['Price'].sort_values(ascending=True).reset_index(drop=True)

x_price = df.loc[df['Price']<260000]
x_price.reset_index(drop=True)

df['Total'].sort_values(ascending=True).reset_index(drop=True)

y_total = df.loc[df['Total']>650000]
y_total.reset_index(drop=True)

plt.plot(x_price['Price'], y_total['Total'],"g--o")
plt.grid(True)
plt.title("Price vs Total")
plt.xlabel("Price")
plt.ylabel("Total")
plt.show()

ta = [11, 12, 12, 13, 13, 13, 14, 14, 14, 14,22,23,24,25,26,28,28,29, 29]

plt.hist(ta, bins=5)
plt.show()

x_price

expload = (.0, .0, .0, .0, .0, .1)

plt.pie(x_price['Price'], labels=x_price['Region'],autopct='%1.1f%%', explode = expload)
plt.title("Price Distribution by Region")
plt.show()

human_gender = ["male", "female"]
fig, ax = plt.subplots(2, 2, figsize=(12, 10))

ax[0,0].plot(x_price['Price'], y_total['Total'],"g--o")
ax[0,0].set_title("Price vs Total")
ax[0,0].set_xlabel("Price")
ax[0,0].set_ylabel("Total")
ax[0,0].grid(True)

ax[0,1].pie(x_price['Price'], labels=x_price['Region'],autopct='%1.1f%%')
ax[0,1].set_title("Price Distribution by Region")


ax[1,0].bar(human_gender,[male_sales["Total"].sum(), female_sales["Total"].sum()], color = ["orange", "black"])
ax[1,0].set_title("Total Sales by Gender")
ax[1,0].set_xlabel("Gender")
ax[1,0].set_ylabel("Total Sales")

ax[1,1].plot([12,13,11,14], "r--o")
ax[1,1].plot([13,10,13,15], "g--o")
ax[1,1].set_title("Price vs Total")
ax[1,1].set_xlabel("Price")
ax[1,1].set_ylabel("Total")


plt.tight_layout()
plt.show()

df.head()

df['PurchaseDate'] = pd.to_datetime(df['PurchaseDate'])
df['Month'] = df['PurchaseDate'].dt.month_name()
df.head()

df.groupby(['Month', 'Gender'])['Total'].sum().reset_index()

